name: Daily event summary

on:
  schedule:
    - cron: "0 7 * * 1-5"

jobs:
  daily_summary:
    runs-on: [self-hosted, linux]
    environment: production
    container: python:3.13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Run script
        run: python3 -u dailysummary.py
