name: Nyhetsjeger event check

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  scrape:
    runs-on: [self-hosted, linux]
    environment: production
    container: python:3.13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Run script
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          SPACES_ACCESS_ID: ${{ secrets.SPACES_ACCESS_ID }}
          SPACES_SECRET_KEY: ${{ secrets.SPACES_SECRET_KEY }}
          BUCKET_URL: ${{ secrets.BUCKET_URL }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        timeout-minutes: 10
        run: python3 -u scrape.py
